[package]
name = "ereea"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.9"
noise = "0.9.0"
rand = "0.9.0"
iced = { version = "0.10", features = ["default", "canvas", "tokio", "debug"] }


[[bin]]
name = "ereea"
path = "src/main.rs"